export const bankIcon = {
  'A': 'bank-card__A',
  'AC': 'bank-card__AC',
  'AD': 'bank-card__AD',
  'B': 'bank-card__B',
  'C': 'bank-card__C',
  'D': 'bank-card__D',
  'E': 'bank-card__E',
  'F': 'bank-card__F',
  'G': 'bank-card__G',
  'I': 'bank-card__I',
  'J': 'bank-card__J',
  'K': 'bank-card__K',
  'M': 'bank-card__M',
  'N': 'bank-card__N',
  'O': 'bank-card__O',
  'P': 'bank-card__P',
  'R': 'bank-card__R',
  'S': 'bank-card__S',
  'T': 'bank-card__T',
  'U': 'bank-card__U',
  'V': 'bank-card__V',
  'W': 'bank-card__W',
  'Y': 'bank-card__Y',
  'Z': 'bank-card__Z',
  'OTHER': 'bank-card__OTHER'
}
